
development: &id001
  adapter: postgresql
  database: 80dd2aa4d59e45d49a7adfdd8a16ccff
  host: dokku-hosted.thruhere.net
  sslcert: /home/dmmmd/projects/python_code/psycopg_connect/certs/postgresql.crt
  sslkey: /home/dmmmd/projects/python_code/psycopg_connect/certs/postgresql.key
  sslmode: require
  user: postgres
production: *id001
test: *id001
